FROM envoyproxy/envoy:v1.29-latest

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

EXPOSE 8299 9901

CMD ["/docker-entrypoint.sh", "envoy", "-c" "/etc/envoy/envoy.yaml"]
