global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # envoy proxy
  - job_name: 'envoy-proxy'
    scrape_interval: 5s
    metrics_path: '/stats/prometheus'
    static_configs:
      - targets: ['envoy:9901']
    # relabel_configs:
    #   - source_labels: [envoy_cluster_name]
    #     regex: 'qwen3.0_cluster'
    #     target_label: upstream_address
    #     replacement: '$1:$2'
    #   - source_labels: [__name__]
    #     regex: 'envoy_cluster_(.+)_upstream_rq_total'
    #     target_label: "instance"
    #     replacement: "$1"
  
  # qwen2.5
  - job_name: 'qwen_2.5'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'qwen2.5_1:8299' 
          - 'qwen2.5_2:8299' 
          - 'qwen2.5_3:8299'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):\\d+'
        target_label: 'service_name'
        replacement: '$1'
  
  # qwen3.0
  - job_name: 'qwen_3.0'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'qwen3.0_1:8299' 
          - 'qwen3.0_2:8299' 
          - 'qwen3.0_3:8299'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):\\d+'
        target_label: 'service_name'
        replacement: '$1' 
