scrape_configs:
  - job_name: 'envoy-proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['envoy:9901']
    metrics_path: '/stats/prometheus'
    relabel_configs:
      - source_labels: [__name__]
        regex: "cluster\\.((.+?)_cluster)"
        target_label: "upstream_address"
        replacement: "$1:8299"      