global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # envoy proxy
  - job_name: 'envoy-proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['envoy:9901']
    metrics_path: '/stats/prometheus'
    relabel_configs:
      - source_labels: [__name__]
        regex: "cluster\\.((.+?)_cluster)"
        target_label: "upstream_address"
        replacement: "$1:8299"      
  
  # qwen2.5
  - job_name: 'qwen_2.5'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'qwen2.5-1:8299' 
          - 'qwen2.5-2:8299' 
          - 'qwen2.5-3:8299' 
  
  # qwen3.0
  - job_name: 'qwen_3.0'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'qwen3.0-1:8299' 
          - 'qwen3.0-2:8299' 
          - 'qwen3.0-3:8299' 
